# Python

1. LISTS

In [ ]:
nums = [10, 20, 30, 40]

In [ ]:
nums[0]

10

In [ ]:
nums[-1]

40

In [ ]:
nums.append(50)

In [ ]:
nums

[10, 20, 30, 40, 50]

In [ ]:
nums.remove(20)
nums

[10, 30, 40, 50]

In [ ]:
nums.pop()

50

INSTEAD OF

In [ ]:
squares = []
for x in range(10):
  squares.append(x**2)
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

write

In [ ]:
squares = [x**2 for x in range(10)]
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

with condition

In [ ]:
evens = [x for x in range(20) if x%2==0]
evens

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

2. TUPLES

In [ ]:
point = (10, 20)

In [ ]:
x, y = point

In [ ]:
#unpacking
print(x)
print(y)

10
20


more variables

In [ ]:
fruits = ("orange", "mango", "apple", "pineapple")
x , *others = fruits
print(x)
print(others)

orange
['mango', 'apple', 'pineapple']


3. SETS

In [ ]:
sets = {1, 2, 3, 3, 4}
print(sets)

{1, 2, 3, 4}


In [ ]:
seen = set()
for x in [1,2,3,4,4]:
  if x in seen:
    print("duplicates", x)
  seen.add(x)

duplicates 4


4. DICTIONARY

In [ ]:
student = {"name" : "Nv",
           "score" : 90}
student

{'name': 'Nv', 'score': 90}

access

In [ ]:
student["name"]

'Nv'

safe access

In [ ]:
student.get("age", 0)

0

add

In [ ]:
student["age"] = 11
student

{'name': 'Nv', 'score': 90, 'age': 11}

iteration

In [ ]:
for key, value in student.items():
  print(key, value)

name Nv
score 90
age 11


EXAMPLE

In [ ]:
nums = [1,2,1,3,2,1]
freq = {}
for x in nums:
  freq[x] = freq.get(x, 0)+1
print(freq)

{1: 3, 2: 2, 3: 1}


5. FUNCTIONS

In [11]:
def add(a, b):
    return (a + b)

In [12]:
add(10, 20)

30

default argument

In [9]:
def greet(name="Neeyati"):
  return f"Hello {name}"

keyword argument

In [13]:
greet(name = "Neeyati")

'Hello Neeyati'

Variable-length positional arguments

In [14]:
def total(*args):
  return sum(args)

Variable-length keyword arguments

In [15]:
def info(**kwargs):
  print(kwargs)

6. Lambda

In [16]:
square = lambda x : x**2

example

In [21]:
students = [
    ("A", 78),
    ("B", 95),
    ("C", 82)
]

students.sort(key=lambda x: x[1])

7. map() and filter()

In [18]:
nums = [1, 2,3,4]
result = list(map(lambda x : x**2, nums))
result

[1, 4, 9, 16]

In [22]:
nums = [1,2,3,4,5,6]
result = list(filter(lambda x: x%2==0, nums))
result

[2, 4, 6]

8. Exception Handling

In [23]:
try:
  x = int(input())
  result = 10/x
except ValueError:
  print("Invalidnumber")
except ZeroDivisionError:
  print("Cannot divide by zero")
else:
  print(result)
finally:
  print("This will always execute")

0
Cannot divide by zero
This will always execute


9. OOP

In [27]:
class Model:
    def __init__(self, name):
        self.name = name

    def train(self):
        print(f"Training {self.name}")

#create object
model = Model("Random Forest")
model.train()

Training Random Forest


10. Inheritance

In [31]:
class Model:
  def train(self):
    print("Training")
class NeuralNetwork(Model):
  def predict(self):
    print("Predicting")

In [32]:
nn = NeuralNetwork()
nn.train() #NeuralNetwork inherits from Model
nn.predict()

Training
Predicting


11. Files

In [33]:
with open("data.txt", "r") as file:
    data = file.read()

In [ ]:
with open("data.txt", "w") as file:
  data = file.write()

Why 'with'?

Because Python automatically closes the file.

# NUMPY

In [34]:
import numpy as np

numpy arrays

In [ ]:
a = np.array([1, 2, 3, 4])

12. numpy arrays vs python lists

In [37]:
a = [1, 2, 3] #python lists
print (a * 2)

[1, 2, 3, 1, 2, 3]


In [36]:
a = np.array([1, 2, 3]) #numpy
print(a * 2)

[2 4 6]


13. Shape

In [39]:
X = np.array([
    [1, 2 ,3],
    [4, 5, 6]]
)

In [40]:
X.shape

(2, 3)

14. Dimensions

In [41]:
X.ndim

2

In [43]:
y = np.array([1,2,3])
y.ndim

1

In [44]:
y.shape

(3,)

In [45]:
z = np.array([
    [1,2],
    [3,4]
])
z.shape

(2, 2)

In [46]:
z.ndim

2

15. Indexing

In [53]:
X = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

1st row

In [54]:
X[0]

array([10, 20, 30])

1st row, 2nd column

In [55]:
X[0, 1]

np.int64(20)

Column

In [58]:
X[:, 1]

array([20, 50, 80])

16. Reshape

In [59]:
a = np.array([1,2,3,4,5,6])

In [60]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

Number of elements must remain equal:
1. 1 × 6
2. 2 × 3
3. 3 × 2
4. 6 × 1,
but not 4 x 2

17. -1 in reshape **

In [63]:
a.reshape(-1, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

18. Axis *****

In [64]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [65]:
X.sum(axis=0)

array([5, 7, 9])

In [66]:
X.sum(axis=1)

array([ 6, 15])

19. Vectorization *****

1. normal loop

In [67]:
result = []

for x in nums:
    result.append(x * 2)

2. vectorized

In [68]:
nums = np.array(nums)
result  = nums * 2

ENTIRE ARRAY ->
optimized vectorized operation ->
ENTIRE RESULT

20. Broadcasting

In [69]:
X = np.array([
    [1,2,3],
    [4,5,6]
])

b = np.array([10,20,30])

In [70]:
X + b

array([[11, 22, 33],
       [14, 25, 36]])

21. Matrix Multiplication

In [71]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

In [75]:
C = A @ B
C

array([[19, 22],
       [43, 50]])

In [76]:
C = np.matmul(A, B)
C

array([[19, 22],
       [43, 50]])

22. Useful NumPy functions

In [81]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [86]:
np.arange(3,8)

array([3, 4, 5, 6, 7])

In [87]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [88]:
np.arange(10, 25, 5)

array([10, 15, 20])

In [89]:
np.arange(10, 2, -2)

array([10,  8,  6,  4])

In [90]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [91]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [92]:
np.linspace(0, 10, num=4, endpoint=False)

array([0. , 2.5, 5. , 7.5])

In [94]:
arr = np.array([10, 20, 30, 40])
result = np.mean(arr)

In [95]:
np.median(arr)

np.float64(25.0)

In [98]:
np.std(arr)

np.float64(11.180339887498949)

In [99]:
np.var(arr)

np.float64(125.0)

In [104]:
arr = np.array([34, 23, 45, 75])
np.min(arr)

np.int64(23)

In [105]:
np.max(arr)

np.int64(75)

In [106]:
np.argmax(arr)

np.int64(3)

In [107]:
np.sum(arr)

np.int64(177)

In [110]:
a = np.array([1,2,3,4,5,6,7,8])

In [112]:
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [114]:
a = np.array([1,2,3])
b = np.array([43,51,62])

In [116]:
np.concatenate((a,b))

array([ 1,  2,  3, 43, 51, 62])

In [117]:
np.stack((a, b), axis=0)

array([[ 1,  2,  3],
       [43, 51, 62]])

In [119]:
print(np.dot(a,b)) #(1*43 + 2*51 + 3*62)

331


In [120]:
a = np.array([[1,2],[3,4]])
b = np.array([[43,51],[62, 2]])

In [121]:
np.matmul(a,b)

array([[167,  55],
       [377, 161]])

In [122]:
print(np.random.rand())

0.9290019533802887


In [124]:
# Generate a 2x3 matrix of floats between 0 and 1
print(np.random.rand(2, 3))

[[0.93698211 0.97419971 0.54168405]
 [0.7717458  0.28130746 0.86049373]]


In [125]:
print(np.random.randn())

0.2734110430056996


In [123]:
# Generate a 2x3 matrix from normal distribution
print(np.random.randn(2, 3))

[[-0.90471053  1.05529983 -0.57823345]
 [-0.01856135 -0.69023839 -0.04997922]]
